[package]
name = "sync-test"
version = "0.1.0"
authors = ["Thom Chiovoloni <tchiovoloni@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
viaduct-reqwest = { path = "../../components/support/viaduct-reqwest" }
logins = { path = "../../components/logins" }
sync15 = { path = "../../components/sync15" }
tabs = { path = "../../components/tabs" }
fxa-client = { path = "../../components/fxa-client" }
url = "2.1"
env_logger = "0.7"
log = "0.4"
anyhow = "1.0"
rand = "0.7"
lazy_static = "1.4"
structopt = "0.3"
