[package]
name = "uniffi"
version = "0.1.0"
authors = ["Firefox Sync Team <sync-team@mozilla.com>"]
license = "MPL-2.0"
edition = "2018"

[dependencies]
weedle = "0.11"
ffi-support = "0.4"
anyhow = "1.0"
