[package]
name = "rc_glean_ffi"
edition = "2018"
version = "0.1.0"
authors = ["Application Services <application-services@mozilla.com>"]
license = "MPL-2.0"

[lib]
name = "rc_glean_ffi"
crate-type = ["lib"]

[dependencies]
log = "0.4"

[dependencies.rc_glean]
path = ".."
